apiVersion: v1
kind: ServiceAccount
metadata:
  name: sms-chatgpt-daemon
  namespace: sms-chatgpt
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sms-chatgpt-daemon
  namespace: sms-chatgpt
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "get", "list", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sms-chatgpt-daemon
  namespace: sms-chatgpt
subjects:
  - kind: ServiceAccount
    name: sms-chatgpt-daemon
    namespace: sms-chatgpt
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sms-chatgpt-daemon
